name: ${project.name}
main: ru.tehkode.modifyworld.bukkit.Modifyworld
soft-depend: [ Vault ]
version: ${project.version}
author: t3hk0d3, bmlzootown
description: World modification permission ruleset
api-version: 1.14
